
x = ['XXXXXXXXXXXXDXXX',
     'XOOEOTOOOOOOOOOX',
     'XOOOOOOOOOOEOOOX',
     'XOOOOOEOOOOOOOOX',
     'XXXXXXOOOOXXXXXX',
     'XXXXXXOOOOXXXXXX',
     'XXXXXXOOOOXXXXXX',
     'XXXXOOOOOOOOXXXX',
     'XXXXOOOOPOOOXXXX',
     'XXXXXXXXDXXXXXXX']

TEMPLATES = [x]
