
x = ['XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXDXX',
     'XOOEOTOOOOOOOOX',
     'XOOOOOOOOOEOOOX',
     'XOOOOOEOOOOOOOX',
     'XXXXXXOOOXXXXXX',
     'XXXXXXOOOXXXXXX',
     'XXXXXXOOOXXXXXX',
     'XXXXOOOOOOOXXXX',
     'XXXXOOOPOOOXXXX',
     'XXXXXXXDXXXXXXX',
     'XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXXXX']

y = ['XXDXXXXXXXXXDXX',
     'XOOOOXXXXXOOOOX',
     'XOOEOXXXXXOEOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOOOOOOOOOOX',
     'XOOOOOOOOOOOOOX',
     'XOOOOOOOPOOOOOX',
     'XXXXXXXXDXXXXXX']

TEMPLATES = [x, y]
# x = ['XXXXXXXXXXXXDXXX',
#      'XOOEOTOOOOOOOOOX',
#      'XOOOOOOOOOOEOOOX',
#      'XOOOOOEOOOOOOOOX',
#      'XXXXXXOOOOXXXXXX',
#      'XXXXXXOOOOXXXXXX',
#      'XXXXXXOOOOXXXXXX',
#      'XXXXOOOOOOOOXXXX',
#      'XXXXOOOOPOOOXXXX',
#      'XXXXXXXXDXXXXXXX']

# y = ['XXDXXXXXXXXXXDXX',
#      'XOOOOXXXXXXOOOOX',
#      'XOOEOXXXXXXOEOOX',
#      'XOOOOXXXXXXOOOOX',
#      'XOOOOXXXXXXOOOOX',
#      'XOOOOXXXXXXOOOOX',
#      'XOOOOOOOOOOOOOOX',
#      'XOOOOOOOOOOOOOOX',
#      'XOOOOOOOOPOOOOOX',
#      'XXXXXXXXXDXXXXXX']

# TEMPLATES = [x, y]
