
x = ['XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXDXX',
     'XOOEOTOOOOOOOOX',
     'XOOOOOOOOOEOOOX',
     'XOOOOOEOOOOOOOX',
     'XXXXXXOOOXXXXXX',
     'XXXXXXOOOXXXXXX',
     'XXXXXXOOOXXXXXX',
     'XXXXOOOOOOOXXXX',
     'XXXXOOOPOOOXXXX',
     'XXXXXXXDXXXXXXX',
     'XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXXXX',
     'XXXXXXXXXXXXXXX']

y = ['XXDXXXXXXXXXDXX',
     'XOOOOXXXXXOOOOX',
     'XOOEOXXXXXOEOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOXXXXXOOOOX',
     'XOOOOOOOOOOOOOX',
     'XOOOOOOOOOOOOOX',
     'XOOOOOOOPOOOOOX',
     'XXXXXXXXDXXXXXX']

TEMPLATES = [x, y]
